### ISSUE TITLE
Composer/autoload support?

### ISSUE THREAD

**Issue by nickurt** [tommoor/fastimage#11]
Add 'composer.json' for autoloading in projects

**Comment by hansott** [comment]
+1

**Comment by hansott** [comment]
@tommoor I can make a PR for you? :-)

**Comment by firejdl** [comment]
@hansott please do! I will use it at least ;)

**Comment by ibarrajo** [comment]
I've done a PR with composer compatibility.
https://github.com/tommoor/fastimage/pull/13

You can also use my fork over here:
https://github.com/ibarrajo/fastimage

**Comment by nickurt** [comment]
Thanks, I moved over to your fork @ibarrajo :+1:
