### ISSUE TITLE
Slow on mine

### ISSUE THREAD

**Issue by sonyarianto** [tommoor/fastimage#5]
I just tested to compare with getimagesize() function and the result also the same. Means maybe the network is the problem.

**Comment by dearsina** [comment]
I just tried it now (PHP 7.4) and it's about 30-40% faster on a small-ish JPG. I am imagining the original size of the image will be a determining factor in how much faster this is because a semi-fixed length of time is required to run the FastImage class regardless of filesize.

**Comment by REDAL** [comment]
@dearsina @tommoor 
does it work with local files?
not just remote ones
does it detect filetype based on file extension, or file internal structure and data
can it detect fake images ?

regards

**Comment by tommoor** [comment]
> does it work with local files?

No. The interface is a uri.

> does it detect filetype based on file extension, or file internal structure and data

Internal structure, as documented 

> can it detect fake images ?

Maybe you'd get 0 bytes but it's not designed for this purpose.

**Comment by REDAL** [comment]
@tommoor 
thanks a lot for your time and answer.
kindest regards
